import {z} from 'zod';
import {identity,readState,saveState,failure} from '@/lib/storage';
import {Case,addEvent,analyze,evidenceStates,stages,timestamp,uid} from '@/lib/model';
export const dynamic='force-dynamic';
export async function GET(){try{const user=await identity();return Response.json({state:await readState(user.userId),user:{name:user.displayName,email:user.email,local:Boolean(user.localAccess),workspaceId:user.workspaceId,localAccess:user.localAccess}},{headers:{'Cache-Control':'no-store'}})}catch(e){return failure(e)}}
const input=z.object({action:z.string(),revision:z.number().int().nonnegative(),caseId:z.string().optional(),payload:z.record(z.unknown()).default({})});
export async function POST(request:Request){try{
 const user=await identity();const origin=request.headers.get('origin');if(origin&&origin!==new URL(request.url).origin)throw new Error('VALIDATION:Invalid request origin.');
 const parsed=input.safeParse(await request.json());if(!parsed.success)throw new Error('VALIDATION:Invalid request.');
 const {action,revision,caseId,payload:p}=parsed.data;const state=await readState(user.userId);if(state.revision!==revision)throw new Error('CONFLICT');
 const str=(k:string,required=false)=>{const value=p[k];if(value!==undefined&&typeof value!=='string')throw new Error('VALIDATION:Invalid '+k);const s=(value as string||'').trim();if(s.length>12000||required&&!s)throw new Error('VALIDATION:Please complete '+k+'.');return s;};
 const choice=(k:string,values:readonly string[])=>{const s=str(k,true);if(!values.includes(s))throw new Error('VALIDATION:Invalid '+k);return s;};
 let c=state.cases.find(c=>c.id===caseId);let createdId:string|undefined;
 if(action==='role'){state.role=choice('role',['Analyst','Partner','Admin']) as typeof state.role;}
 else if(action==='create'){
 const companyId=str('companyId');let company=companyId?state.companies.find(c=>c.id===companyId):undefined;if(companyId&&!company)throw new Error('VALIDATION:Company not found.');
 if(!company){const website=str('website',true);try{if(!['http:','https:'].includes(new URL(website).protocol))throw 0;}catch{throw new Error('VALIDATION:Enter a valid https:// company website.');}company={id:uid(),name:str('companyName',true),website,sector:str('sector',true),geography:str('geography',true)};state.companies.push(company);}
 c={id:`CASE-${new Date().getFullYear()}-${uid().slice(0,8).toUpperCase()}`,companyId:company.id,name:str('name')||`${str('investmentStage',true)} investment opportunity`,investmentStage:str('investmentStage',true),stage:'Sourced',owner:str('owner')||user.displayName,thesis:str('thesis'),strategy:str('strategy'),roundSize:str('roundSize'),checkSize:str('checkSize'),valuation:str('valuation'),source:str('source'),lead:str('lead'),notes:str('notes'),createdAt:timestamp(),docs:[],evidence:[],runs:[],questions:[],reviews:[],recommendations:[],decisions:[],activity:[]};addEvent(c,'Investment case created.',user.displayName);state.cases.unshift(c);createdId=c.id;
 }else{if(!c)throw new Error('VALIDATION:Investment case not found.');
 switch(action){
 case 'edit':{const before={stage:c.stage,owner:c.owner,thesis:c.thesis,notes:c.notes};for(const k of ['name','investmentStage','owner','thesis','strategy','roundSize','checkSize','valuation','source','lead','notes'] as const)c[k]=str(k,k==='name'||k==='owner'||k==='investmentStage');addEvent(c,`Case context updated. Previous context: ${JSON.stringify(before)}`,user.displayName);break;}
 case 'stage':{const stage=choice('stage',stages.filter(s=>!['Invested','Passed'].includes(s)));const previous=c.stage;c.stage=stage;addEvent(c,`Stage changed: ${previous} → ${c.stage}. Historical decisions retained.`,user.displayName);break;}
 case 'evidence':{const docId=str('documentId');const doc=c.docs.find(d=>d.id===docId);if(docId&&!doc)throw new Error('VALIDATION:Source document not found.');c.evidence.push({id:uid(),label:str('label',true),value:str('value',true),status:choice('status',evidenceStates) as typeof evidenceStates[number],kind:choice('kind',['Company claim','Structured fact','Financial metric','External evidence']),source:doc?.name||str('source',true),locator:str('locator'),documentId:docId,excerpt:str('excerpt',true),createdAt:timestamp(),author:user.displayName});addEvent(c,`Evidence recorded: ${str('label')}.`,user.displayName);break;}
 case 'resolveEvidence':{const e=c.evidence.find(e=>e.id===str('id',true));if(!e)throw new Error('VALIDATION:Evidence not found.');const previous=JSON.stringify(e);e.status=choice('status',evidenceStates) as typeof e.status;e.resolution=str('resolution',true);addEvent(c,`Evidence review: ${e.label} → ${e.status}. ${e.resolution} | Original entry: ${previous}`,user.displayName);break;}
 case 'analysis':{const run=analyze(c,str('name',true));c.runs.unshift(run);addEvent(c,`Simulated analysis completed: ${run.name} (${run.id}). Input evidence snapshot preserved.`,user.displayName);break;}
 case 'question':{const trigger=str('trigger');if(trigger&&!c.evidence.some(e=>e.id===trigger))throw new Error('VALIDATION:Evidence not found.');c.questions.unshift({id:uid(),text:str('text',true),category:str('category',true),priority:choice('priority',['High','Normal','Low']),owner:str('owner',true),status:'Open',trigger,resolution:'',createdAt:timestamp()});addEvent(c,`Diligence question added: ${str('text')}`,user.displayName);break;}
 case 'questionStatus':{const q=c.questions.find(q=>q.id===str('id',true));if(!q)throw new Error('VALIDATION:Question not found.');q.status=choice('status',['Open','Requested','Answered','Resolved','Blocked']);q.resolution=str('resolution',q.status==='Resolved'||q.status==='Answered');addEvent(c,`Diligence ${q.status.toLowerCase()}: ${q.text}. ${q.resolution}`,user.displayName);break;}
 case 'review':case 'recommendation':case 'decision':{
 if(action==='decision'&&state.role==='Analyst')throw new Error('VALIDATION:Switch to the Partner or Admin prototype role to record a final decision.');
 const outcome=choice('outcome',action==='review'?['Agree','Disagree','Add Context','Override','Comment']:action==='recommendation'?['Advance','Monitor','Pass','Request More Diligence']:['Invested','Pass','Monitor','More Diligence']);
 const runId=str('runId');if(action==='review'&&!c.runs.some(r=>r.id===runId))throw new Error('VALIDATION:Select an analysis run.');
 const j={id:uid(),outcome,rationale:str('rationale',true),author:user.displayName,createdAt:timestamp(),participants:action==='decision'?str('participants',true):undefined,runId:runId||undefined};
 if(action==='review')c.reviews.unshift(j);if(action==='recommendation')c.recommendations.unshift(j);if(action==='decision'){c.decisions.unshift(j);c.stage=outcome==='Pass'?'Passed':outcome==='More Diligence'?'Due Diligence':outcome;}
 addEvent(c,`${action==='review'?'Human review':action==='recommendation'?'Analyst recommendation':'Final decision'}: ${outcome}. ${j.rationale}`,user.displayName);break;}
 case 'portfolio':{if(c.decisions[0]?.outcome!=='Invested')throw new Error('VALIDATION:Record an Invested decision before portfolio entry.');if(c.portfolio)throw new Error('VALIDATION:This case already has a portfolio record.');if(state.role==='Analyst')throw new Error('VALIDATION:Partner or Admin role required.');c.portfolio={date:str('date',true),ownership:str('ownership'),valuation:str('valuation'),thesis:c.thesis,updates:[]};addEvent(c,'Portfolio record created. Investment case and source history retained.',user.displayName);break;}
 case 'monitoring':{if(!c.portfolio)throw new Error('VALIDATION:Portfolio record not found.');c.portfolio.updates.unshift({id:uid(),date:str('date',true),type:str('type',true),expected:str('expected'),actual:str('actual',true),note:str('note'),author:user.displayName});addEvent(c,`Manual portfolio update: ${str('type')}. ${str('actual')}`,user.displayName);break;}
 default:throw new Error('VALIDATION:Unknown action.');}}
 return Response.json({state:await saveState(user.userId,state,revision),createdId});
 }catch(e){return failure(e)}}
