import {Case,WorkspaceState,analyze,addEvent} from './model';
// All companies, documents, metrics and judgments in this module are fictional fixtures.
export function seed():WorkspaceState{
 const specs=[['Aster Robotics','Industrial automation','Singapore','Series A','IC Review'],['TerraGrid','Climate software','Indonesia','Seed','Due Diligence'],['Nexa Systems','Enterprise software','Singapore','Series A','Due Diligence'],['Meridian Health','Health technology','Malaysia','Seed','Passed'],['Aster Robotics','Industrial automation','Singapore','Seed','Invested']];
 const companies=specs.slice(0,4).map((s,i)=>({id:`company-${i}`,name:s[0],website:`https://${s[0].toLowerCase().replaceAll(' ','')}.example`,sector:s[1],geography:s[2]}));
 const cases:Case[]=specs.map((s,i)=>{
 const date='2026-09-10T09:00:00.000Z';
 const c:Case={id:`CASE-2026-00${41+i}`,companyId:`company-${i===4?0:i}`,name:`${s[3]} investment opportunity`,stage:s[4],investmentStage:s[3],owner:i===1?'Maya Chen':'Alex Morgan',thesis:'Back capital-efficient businesses solving operational problems in Southeast Asia.',strategy:'Early-stage technology · sample strategy',roundSize:'USD 8,000,000',checkSize:'USD 1,500,000',valuation:'Not confirmed',source:'Founder introduction · sample',lead:'Unknown',notes:'Fictional case for product exploration. All source excerpts and judgments are demo content.',createdAt:date,docs:[],evidence:[],runs:[],questions:[],reviews:[],recommendations:[],decisions:[],activity:[]};
 c.docs=[{id:`doc-${i}-deck`,name:`${s[0]} — pitch deck.txt`,type:'Pitch Deck',source:'Founder · fictional sample',size:0,createdAt:date,author:'Alex Morgan',processing:'Sample source',sampleText:`FICTIONAL DEMO SOURCE\n${s[0]} | Pitch deck excerpt\nPage 12 — Traction\nAnnual recurring revenue: USD 4.2 million.\nActive customers: 145.\nAll values are illustrative company claims, not verified facts.`}];
 c.evidence=[{id:`ev-${i}-arr`,label:'Annual recurring revenue',value:'USD 4.2 million',status:i===1?'Reported':'Supported',kind:'Financial metric',source:c.docs[0].name,locator:'Page 12 · Traction',documentId:c.docs[0].id,excerpt:'Annual recurring revenue: USD 4.2 million.',createdAt:date,author:'Alex Morgan'}];
 if(i!==1){const supporting={id:`doc-${i}-finance`,name:`${s[0]} — revenue summary.txt`,type:'Financial Model',source:'Finance team · fictional sample',size:0,createdAt:date,author:'Alex Morgan',processing:'Sample source',sampleText:'FICTIONAL DEMO SOURCE\nRevenue summary\nAnnual recurring revenue: USD 4.2 million.\nThis sample finance summary supports the sample pitch deck claim; no real verification has taken place.'};c.docs.push(supporting);c.evidence[0].source='Pitch deck + revenue summary';c.evidence[0].documentId=supporting.id;c.evidence[0].locator='Revenue summary / deck p.12';c.evidence[0].excerpt='Deck reports USD 4.2 million ARR. The fictional finance summary also reports USD 4.2 million ARR.';}
 if(i===2){c.docs.push({id:'doc-2-model',name:'Nexa Systems — customer ledger.txt',type:'Financial Model',source:'Company · fictional sample',size:0,createdAt:date,author:'Alex Morgan',processing:'Sample source',sampleText:'FICTIONAL DEMO SOURCE\nCustomer ledger, September 2026\nActive customers: 128.\nCustomer definitions have not been reconciled with the pitch deck.'});c.evidence.push({id:'ev-2-customers',label:'Active customers',value:'145 (deck) / 128 (ledger)',status:'Conflicting',kind:'Company claim',source:'Pitch deck + customer ledger',locator:'Deck p.12 / ledger summary',documentId:'doc-2-model',excerpt:'Deck: 145 active customers. Ledger: 128 active customers.',createdAt:date,author:'Alex Morgan'});}
 if(i===1)c.evidence.push({id:'ev-1-gap',label:'Top-five customer concentration',value:'Unknown',status:'Unknown',kind:'Structured fact',source:'Missing information',locator:'',documentId:'',excerpt:'No customer-level revenue breakdown has been supplied.',createdAt:date,author:'Maya Chen'});
 if(i<3)c.questions.push({id:`q-${i}`,text:i===2?'Why do the deck and ledger report different customer totals?':i===1?'What share of revenue comes from the five largest customers?':'Can customer references corroborate deployment expansion?',category:'Traction',priority:i===2?'High':'Normal',owner:c.owner,status:'Open',trigger:c.evidence.at(-1)!.id,resolution:'',createdAt:date});
 const run=analyze(c,'Initial screening');run.createdAt=date;if(i===0||i===3||i===4){run.assessment='Positive · sample assessment';run.findings[0].interpretation='Sample interpretation: reported recurring revenue supports further review of commercial traction.';}c.runs=[run];
 if(i===1)c.recommendations.push({id:'rec-1',outcome:'Request More Diligence',rationale:'Customer concentration remains unknown.',author:'Maya Chen',createdAt:date});
 if(i===3){c.recommendations.push({id:'rec-3',outcome:'Pass',rationale:'Outside the current fund mandate despite encouraging company traction.',author:'Alex Morgan',createdAt:date});c.decisions.push({id:'dec-3',outcome:'Pass',rationale:'The partnership chose not to proceed because the mandate does not cover this investment.',participants:'Sample partnership',author:'Sample Partner',createdAt:date});}
 if(i===4){c.recommendations.push({id:'rec-4',outcome:'Advance',rationale:'Customer diligence supports the initial thesis.',author:'Alex Morgan',createdAt:date});c.decisions.push({id:'dec-4',outcome:'Invested',rationale:'Fictional historical investment, retained for follow-on context.',participants:'Sample partnership',author:'Sample Partner',createdAt:date});c.portfolio={date:'2025-08-15',ownership:'8% · sample',valuation:'USD 18m · sample',thesis:c.thesis,updates:[{id:'update-4',date:'2026-09-10',type:'Revenue Update',expected:'Reach USD 4m ARR by September 2026',actual:'USD 4.2m ARR reported',note:'Manual sample update; verify against financial records.',author:'Alex Morgan'}]};}
 addEvent(c,'Sample case created with fictional evidence and analysis.','System · demo');return c;});
 return {revision:0,role:'Analyst',companies,cases};
}
