import {Case,Company,evidenceStates,stages} from '@/lib/model';
export type Field={key:string;label:string;type?:string;options?:string[];choices?:{value:string;label:string}[];required?:boolean;value?:string};
export type FormSpec={title:string;description:string;action:string;fields:Field[];extra?:Record<string,string>;caseId?:string};
const field=(key:string,label:string,required=false,type='text',value=''):Field=>({key,label,required,type,value});
const select=(key:string,label:string,options:string[],value?:string):Field=>({key,label,options,value});
export function caseForm(user:string,company?:Company):FormSpec{return {title:'New investment case',description:'Open a working case with the essentials. Add sources and enrich investment context as information becomes available. New cases begin as Sourced.',action:'create',extra:company?{companyId:company.id}:undefined,fields:[...(company?[]:[field('companyName','Company name',true),field('website','Company website (https://)',true,'url'),field('sector','Sector / industry',true),field('geography','Geography',true)]),select('investmentStage','Investment stage',['Pre-seed','Seed','Series A','Series B','Growth','Other']),field('name','Case name'),field('owner','Deal owner',false,'text',user),field('thesis','Investment thesis',false,'textarea')]}}
export function contextForm(c:Case):FormSpec{const keys=['name','investmentStage','owner','strategy','thesis','roundSize','checkSize','valuation','source','lead','notes'] as const;const labels=['Case name','Investment stage','Deal owner','Fund / strategy','Investment thesis','Round size (include currency)','Target check (include currency)','Valuation (include currency)','Deal source','Lead investor','Internal notes'];return {title:'Enrich case context',description:'Maintain this case as information develops: strategy, deal terms, thesis and notes. Company quality and investment fit remain separate judgments.',action:'edit',fields:keys.map((k,i)=>field(k,labels[i],i<3,['notes','thesis'].includes(k)?'textarea':'text',c[k]))}}
export function stageForm(c:Case):FormSpec{return {title:'Update lifecycle',description:'PROTOTYPE ASSUMPTION: stages are manually editable. Reopening retains all historical decisions. Invested and Passed are set through final decisions.',action:'stage',fields:[select('stage','Lifecycle stage',stages.filter(s=>!['Passed','Invested'].includes(s)),c.stage)]}}
export function uploadForm():FormSpec{return {title:'Add source document',description:'Private document storage. Automatic extraction is not enabled. Maximum 20 MB per file.',action:'upload',fields:[field('file','Document',true,'file'),select('type','Document type',['Pitch Deck','Financial Model','Data Room','Additional Document','Meeting Notes']),field('source','Source / provenance',true)]}}
export function evidenceForm(c:Case):FormSpec{return {title:'Record evidence',description:'Capture what the source says. Keep claims and verification status explicit.',action:'evidence',fields:[field('label','Fact or claim',true),field('value','Reported value / statement',true),select('kind','Information class',['Company claim','Structured fact','Financial metric','External evidence']),select('status','Evidence status',[...evidenceStates]),{key:'documentId',label:'Source document',choices:[{value:'',label:'Manual note / external source'},...c.docs.map(d=>({value:d.id,label:d.name}))]},field('source','Source name (required for manual entries)'),field('locator','Page, sheet, cell, or URL'),field('excerpt','Source excerpt or missing-information explanation',true,'textarea')]}}
export function analysisForm():FormSpec{return {title:'Run basic analysis',description:'Simulated evidence review. Saves an input snapshot and flags missing, reported, and conflicting evidence. It does not extract documents or make investment decisions.',action:'analysis',fields:[select('name','Analysis context',['Initial Screening','Post-Founder-Meeting','Due Diligence','Pre-IC'])]}}
export function questionForm(c:Case):FormSpec{return {title:'New diligence question',description:'Turn uncertainty into a specific follow-up with an owner.',action:'question',fields:[field('text','Question',true,'textarea'),field('category','Category',true,'text','Traction'),select('priority','Priority',['Normal','High','Low']),field('owner','Owner',true,'text',c.owner),{key:'trigger',label:'Triggering evidence',choices:[{value:'',label:'Manual question'},...c.evidence.map(e=>({value:e.id,label:e.label}))]}]}}
export function judgmentForm(kind:string,runId=''):FormSpec{return {title:kind==='review'?'Add human review':kind==='recommendation'?'Save analyst recommendation':'Record final decision',description:'A new historical record is created. Earlier judgments and AI assessments remain intact.',action:kind,extra:kind==='review'?{runId}:undefined,fields:[select('outcome',kind==='review'?'Review response':'Outcome',kind==='review'?['Agree','Disagree','Add Context','Override','Comment']:kind==='recommendation'?['Advance','Request More Diligence','Monitor','Pass']:['Invested','Pass','Monitor','More Diligence']),field('rationale','Rationale',true,'textarea'),...(kind==='decision'?[field('participants','Decision participants',true)]:[])]}}
export function portfolioForm():FormSpec{return {title:'Create portfolio record',description:'PROTOTYPE ASSUMPTION: explicit portfolio entry after an Invested decision. This does not execute a transaction.',action:'portfolio',fields:[field('date','Initial investment date',true,'date',new Date().toISOString().slice(0,10)),field('ownership','Ownership (if known)'),field('valuation','Entry valuation (include currency)')]}}
export function monitoringForm(c:Case):FormSpec{return {title:'Add portfolio update',description:'Manual monitoring. Expected milestones and actual outcomes are recorded by a human.',action:'monitoring',caseId:c.id,fields:[field('date','Update date',true,'date',new Date().toISOString().slice(0,10)),select('type','Event type',['Revenue Update','Fundraising','Leadership Change','Thesis Review','Other']),field('expected','Expected milestone / thesis baseline',false,'textarea'),field('actual','Actual reported outcome',true,'textarea'),field('note','Source / review notes',false,'textarea')]}}
