import {env} from 'cloudflare:workers';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {seed} from './fixtures';
import type {WorkspaceState} from './model';
export async function identity(){const u=await getChatGPTUser();if(!u)throw new Error('AUTH_REQUIRED');return u;}
export function database(){if(!env.DB)throw new Error('Storage unavailable');return env.DB;}
export function bucket(){if(!env.BUCKET)throw new Error('Document storage unavailable');return env.BUCKET;}
export async function readState(owner:string){const db=database();if(owner.startsWith('local_'))await db.prepare('CREATE TABLE IF NOT EXISTS workspaces (owner text PRIMARY KEY NOT NULL, data text NOT NULL, revision integer DEFAULT 0 NOT NULL)').run();let row=await db.prepare('SELECT data, revision FROM workspaces WHERE owner = ?').bind(owner).first<{data:string;revision:number}>();if(!row){const state=seed();await db.prepare('INSERT OR IGNORE INTO workspaces (owner,data,revision) VALUES (?,?,0)').bind(owner,JSON.stringify(state)).run();row=await db.prepare('SELECT data,revision FROM workspaces WHERE owner=?').bind(owner).first<{data:string;revision:number}>();}if(!row)throw new Error('Storage unavailable');return {...JSON.parse(row.data),revision:row.revision} as WorkspaceState;}
export async function saveState(owner:string,state:WorkspaceState,revision:number){state.revision=revision+1;const r=await database().prepare('UPDATE workspaces SET data=?, revision=? WHERE owner=? AND revision=?').bind(JSON.stringify(state),state.revision,owner,revision).run();if(!r.meta.changes)throw new Error('CONFLICT');return state;}
export function failure(e:unknown){const message=e instanceof Error?e.message:'Unexpected failure';console.error('Workspace operation failed',message);return Response.json({error:message==='AUTH_REQUIRED'?'Sign in to continue.':message==='CONFLICT'?'This case changed in another session. Reload the workspace and try again.':message.startsWith('VALIDATION:')?message.slice(11):'Unable to save or load the workspace. Your input has been kept. Please retry.'},{status:message==='AUTH_REQUIRED'?401:message==='CONFLICT'?409:message.startsWith('VALIDATION:')?400:503});}
